//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int ex_ID { get; set; }
        public string ex_Name { get; set; }
        public string ex_Type { get; set; }
        public int cals_Burned { get; set; }

    }
}
