//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Calories { get; set; }

        /// <summary>
        /// Converts ingredient to a string able to be printed to console
        /// </summary>
        /// <returns>Ingredient as a string</returns>
        public override string ToString()
        {

            return String.Format("ID: {0} Name: {1} Calories: {2}", ID, Name, Calories);

        }
    }
}
